name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt update; sudo apt install -y build-essential libreadline8 libreadline-dev

      - name: Compile
        run: make

      - name: Run program
        run: ./minishell < inputs.txt
