name: MINISHELL_TESTER

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run:  sudo apt update; sudo apt install -y build-essential libreadline8 libreadline-dev valgrind python3 pipx

      - name: Compile
        run: make

      - name: Run program
        run: ./minishell < inputs.txt

      - name: Run with valgrind
        run: valgrind --leak-check=full --show-leak-kinds=all --track-fds=yes --suppressions=readline.supp -q ./minishell < inputs.txt

      - name: Install norminette
        run: pipx install norminette
        
      - name: Run norminette
        id: norm
        continue-on-error: true
        run: |
          norminette . | tee norm.txt
          norm_exit=${PIPELINE[0]}
          echo $norm_exit
      - name: Final result (For norminette)
        run: |
          echo "Errors"
          error_count=$(grep -c "Error" norm.txt || true)
          if [[ "${{ steps.norm.outcome }}" == "success" ]]; then
          echo -e "\033[0;32m✅ Norminette succeeded\033[0m"
          else
          echo -e "\033[0;31m❌ Norminette failed with $NORM_EXIT_CODE error(s)\033[0m"
          fi
