name: MINISHELL_TESTER

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run:  sudo apt update; sudo apt install -y build-essential libreadline8 libreadline-dev valgrind python3 pipx

      - name: Compile
        run: make

      - name: Run program
        run: ./minishell < inputs.txt

      - name: Run with valgrind
        run: valgrind --leak-check=full --show-leak-kinds=all --track-fds=yes --suppressions=readline.supp -q ./minishell < inputs.txt

      - name: Install norminette
        run: pipx install norminette
        
      - name: Run norminette
        id: norm
        run: norminette
        continue-on-error: true

      - name: Final result (For norminette)
        run: |
          if [[ "${{ steps.norm.outcome }}" == "success" ]]; then
            # Green text: \033[0;32m … \033[0m
            echo -e "\033[0;32m✅ Norminette succeeded\033[0m"
          else
            # Red text: \033[0;31m … \033[0m
            echo -e "\033[0;31m❌ Norminette failed\033[0m"
          fi
